import { NextRequest, NextResponse } from 'next/server';
import { getCrawl, getScan } from '@/lib/scanner/store';
import { calculateSiteScore, aggregateViolations, generatePageSummaries } from '@/lib/scoring/site-calculator';
import type { SiteReportData } from '@/lib/types/crawl';

export async function GET(
  _request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;
  const crawl = getCrawl(id);

  if (!crawl) {
    return NextResponse.json({ error: 'Crawl not found' }, { status: 404 });
  }

  if (crawl.status !== 'complete') {
    return NextResponse.json(
      { error: `Crawl is not complete (status: ${crawl.status})` },
      { status: 409 }
    );
  }

  const pageRecords = crawl.pageIds
    .map((pid) => getScan(pid))
    .filter((s) => s != null);

  const siteScore = crawl.siteScore ?? calculateSiteScore(pageRecords);
  const aggregatedViolations = crawl.aggregatedViolations ?? aggregateViolations(pageRecords);
  const pageSummaries = generatePageSummaries(pageRecords);

  const report: SiteReportData = {
    seedUrl: crawl.seedUrl,
    scanDate: crawl.completedAt ?? crawl.startedAt,
    engineVersion: '1.0.0',
    siteScore,
    aggregatedViolations,
    pageSummaries,
    config: crawl.config,
    aodaNote:
      'This report provides an automated assessment based on WCAG 2.2 guidelines and the Accessibility for Ontarians with Disabilities Act (AODA) requirements. Automated tools can detect approximately 30-40% of accessibility issues. A comprehensive AODA compliance assessment requires additional manual testing, assistive technology testing, and expert review.',
    disclaimer:
      'This accessibility report is generated by automated scanning tools and is provided for informational purposes only. It does not constitute legal advice or a guarantee of AODA/WCAG compliance. Organizations should consult with accessibility professionals for a complete compliance assessment.',
  };

  return NextResponse.json(report);
}
